// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jffbarohumllsyubyrkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmZmJhcm9odW1sbHN5dWJ5cmt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDMyNTIsImV4cCI6MjA2MDQ3OTI1Mn0.U_Bf3Y4IRBT-r2Et40Yx7tq20od52sBh-n6pNXRd_u4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);