
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvwxxajojqxfciqqnfij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2d3h4YWpvanF4ZmNpcXFuZmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDc2NDgsImV4cCI6MjA2MDgyMzY0OH0.BpMSvhWt8DHtzJDCGWwkBR-ttsPGmsOGGHJv7rtQg38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);
